
import React from 'react';
import { FiX, FiMessageSquare, FiBook } from 'react-icons/fi';
import { ChatMessage } from './ChatComponents';

export function RemediationModal({ 
  activeSolution, 
  onClose, 
  loading 
}) {
  if (!activeSolution) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="solution-modal-page" onClick={e => e.stopPropagation()}>
        <div className="modal-top-bar">
          <div className="risk-level-badge critical">Security Audit</div>
          <h2>AI Security Remediation</h2>
          <button className="modal-close-icon" onClick={onClose}>
            <FiX size={22} />
          </button>
        </div>

        <div className="modal-content-grid">
          <div className="modal-sidebar-info">
            <div className="sidebar-info-block">
              <label>Remediation Type</label>
              <span>{loading ? 'Orchestrating Agents...' : 'AI Patch Generation'}</span>
            </div>
            
            <div className="sidebar-info-block">
              <label>Target Module</label>
              <span style={{ fontSize: '13px', wordBreak: 'break-all' }}>{activeSolution.title?.split(':').pop() || 'Selected Context'}</span>
            </div>

            <div className="sidebar-info-block">
              <label>Confidence Metrics</label>
              <div className="metric-row">
                <span className="metric-val">{activeSolution.confidence || '95%'}</span>
                <span className="metric-label">Precision</span>
              </div>
            </div>

            <div className="sidebar-info-block">
              <label>Security Status</label>
              <div className="metric-row">
                <span className="metric-val">#BS-{activeSolution.auditId || Math.floor(Math.random() * 9000) + 1000}</span>
                <span className="metric-label">Audit ID</span>
              </div>
            </div>

            <div className="sidebar-info-block">
              <label>Executive Guidance</label>
              <p className="sidebar-para" style={{ color: 'rgba(255,255,255,0.4)', fontSize: '12px' }}>
                This remediation was generated by a multi-agent consensus. Our 'Staff Engineer' agent has verified the patch for architectural integrity.
              </p>
            </div>
          </div>

          <div className="modal-main-remedy">
            <div className="remedy-header-strip">
              <div className="remedy-badge">Security Patch v1.1</div>
              <div className="remedy-badge">Context-Aware</div>
            </div>

            {loading ? (
              <div className="remediation-spinner-view">
                <div className="scan-spinner large" />
                <h3>Synthesizing Solution...</h3>
                <p>Analyzing cross-file dependencies and drafting a secure implementation plan using your existing coding patterns.</p>
              </div>
            ) : (
              <div className="markdown-chat solution-editor-view animate-fade-in">
                <ChatMessage msg={{ role: 'bot', text: activeSolution.content }} noTitle />
              </div>
            )}
          </div>
        </div>

        <div className="modal-bottom-actions">
          <button className="btn-modal-secondary" onClick={onClose}>Close Report</button>
          <button className="btn-modal-primary" onClick={() => {
            navigator.clipboard.writeText(activeSolution.content);
            alert('Security patch copied to clipboard!');
          }}>
            Copy Implementation
          </button>
        </div>
      </div>
    </div>
  );
}
